name: CI for FastAPI

on:
  push:
    branches:
      - main
    
jobs:
  build:
    runs-on: self-hosted

    steps:

    - name: Criar um arquivo no /tmp
      run: |
        echo 'Teste 2' > /tmp/thiago-30-08.txt
